import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Conteúdo programático completo do Auditor-Fiscal RFB
const EDITAL_AFRFB = [
  {
    modulo: "Módulo I – Conhecimentos Básicos",
    disciplinas: [
      { nome: "Língua Portuguesa", topicos: ["Gênero do texto (literário e não literário, narrativo, descritivo e argumentativo)","Interpretação e organização interna do texto","Semântica: sentido e emprego dos vocábulos; campos semânticos","Emprego de tempos e modos dos verbos em português","Morfologia: reconhecimento, emprego e sentido das classes gramaticais","Processos de formação de palavras","Mecanismos de flexão dos nomes e verbos","Sintaxe: frase, oração e período; termos da oração","Processos de coordenação e subordinação","Concordância nominal e verbal","Transitividade e regência de nomes e verbos","Padrões gerais de colocação pronominal no português","Mecanismos de coesão textual","Ortografia","Acentuação gráfica","Emprego do sinal indicativo de crase","Pontuação","Reescrita de frases: substituição, deslocamento, paralelismo","Variação linguística: norma culta"] },
      { nome: "Língua Inglesa", topicos: ["Conhecimento e uso das formas contemporâneas da linguagem inglesa","Compreensão e interpretação de textos variados","Domínio do vocabulário e da estrutura da língua","Ideias principais e secundárias, explícitas e implícitas","Relações intratextuais e intertextuais","Itens gramaticais relevantes para a compreensão dos conteúdos semânticos","Palavras e expressões equivalentes","Elementos de referência"] },
      { nome: "Raciocínio Lógico-Matemático", topicos: ["Lógica: proposições, conectivos, equivalências lógicas, quantificadores e predicados","Conjuntos e suas operações, diagramas","Números inteiros, racionais e reais e suas operações, porcentagem e juros","Proporcionalidade direta e inversa","Medidas de comprimento, área, volume, massa e tempo","Estrutura lógica de relações arbitrárias entre pessoas, lugares, objetos ou eventos fictícios","Dedução de novas informações das relações fornecidas","Raciocínio verbal, matemático, sequencial, orientação espacial e temporal","Formação de conceitos, discriminação de elementos","Compreensão de dados apresentados em gráficos e tabelas","Raciocínio lógico envolvendo problemas aritméticos, geométricos e matriciais","Problemas de contagem e noções de probabilidade","Geometria básica: ângulos, triângulos, polígonos, distâncias, proporcionalidade, perímetro e área","Noções de estatística: média, moda, mediana e desvio padrão","Plano cartesiano: sistema de coordenadas, distância","Problemas de lógica e raciocínio"] },
      { nome: "Estatística", topicos: ["Estatística descritiva","Probabilidade e distribuições de probabilidade","Inferência: estimação pontual e intervalar","Testes de hipóteses","Predição: abordagens; séries temporais","Regressão linear simples e múltipla","Regressão logística"] },
      { nome: "Economia e Finanças Públicas", topicos: ["Conceitos básicos: problema econômico fundamental, mercado, fluxos econômicos","Demanda e oferta, deslocamento das curvas","Elasticidades da oferta e da demanda","Teoria do Consumidor: restrição orçamentária, curvas de indiferença, utilidade","Bens substitutos e complementares, escolha do consumidor, índices de Laspeyres e Paasche","Efeito renda e efeito substituição, demanda de mercado, excedente do consumidor","Escolha sob incerteza: preferências em relação ao risco","Produção: fatores de produção, custos de produção, isoquantas, rendimentos decrescentes","Mercados competitivos: concorrência perfeita, maximização de lucros, equilíbrio de mercado","Poder de mercado: monopólio, monopsônio, oligopólio","Noções de teoria dos jogos: dilema do prisioneiro, equilíbrio de Nash","Eficiência econômica: trocas, livre comércio, vantagem comparativa","Falhas de mercado: assimetria de informação, risco moral, seleção adversa, bens públicos, externalidades","Economia comportamental: aversão à perda, comportamento de manada","Contas Nacionais: produto, renda, despesa, consumo, investimento, poupança","Exportações e importações, balanço de pagamentos e taxas de câmbio","Inflação, índices de preços","Política monetária e taxas de juros","Política fiscal: tributos e gastos do governo","Ciclos econômicos, modelo IS-LM, Plano Real","Déficit orçamentário e dívida pública, teto de gastos","Globalização, G20 e organismos internacionais","Funções econômicas do Estado: alocativa, distributiva e estabilizadora","Orçamento público e parâmetros da política fiscal no Brasil","Responsabilidade fiscal, regras fiscais","Ingressos públicos: conceito, classificação, tipos","Tributação: incidência tributária, perda de peso morto","Carga tributária: conceito, composição, evolução no Brasil","Princípios de descentralização fiscal: transferências intergovernamentais"] },
      { nome: "Administração Geral", topicos: ["Teoria da administração e das organizações","Funções de administração: planejamento, organização, direção e controle","Papéis e habilidades do administrador","Planejamento estratégico: conceitos, princípios, etapas, níveis, métodos e ferramentas","Planejamento tático e operacional","Administração por objetivos","Estrutura organizacional: departamentalização, centralização e descentralização","Processo decisório: tipos de decisões, decisão racional, heurísticas","Comportamento organizacional: cultura, motivação, liderança, comunicação, equipes","Controle: tipos de controle, sistemas de controle, Balanced Scorecard","Gestão de pessoas: recrutamento, seleção, treinamento, desenvolvimento, avaliação","Gestão por competências","Gestão da qualidade: principais teóricos, ferramentas","Gestão de projetos: modelos, etapas, elaboração, técnicas de análise","Gestão de processos, BPM, mapeamento, análise e melhoria de processos","Administração Financeira: alavancagem operacional e financeira, planejamento financeiro","Conceitos básicos de análise de balanços e demonstrações financeiras"] },
      { nome: "Administração Pública", topicos: ["Reformas administrativas e redefinição do papel do Estado","Reforma do serviço civil: mérito, flexibilidade e responsabilização","Do modelo racional-legal ao paradigma pós-burocrático","O Estado oligárquico, autoritário, do bem-estar e regulador","Processos participativos: conselhos de gestão, orçamento participativo","Governo eletrônico, transparência, controle social e accountability","Gestão por resultados na produção de serviços públicos","Comunicação na gestão pública e gestão de redes organizacionais","Administração de compras e materiais: processos de compras governamentais","Normas para licitações: Leis nº 8.666/1993 e 14.133/2021","Mudanças institucionais: organizações sociais, OSCIP, agências reguladoras","Governança Pública: conceitos, princípios, diretrizes, sistema e práticas","Gestão de Riscos: princípios, técnicas, modelos, processo","Formulação e desenvolvimento de políticas públicas","Planejamento e avaliação nas políticas públicas","Lei de Acesso à Informação (Lei nº 12.527/2011)","Lei da Transparência (Lei Complementar nº 131/2009)"] },
      { nome: "Auditoria", topicos: ["Normas Brasileiras de Contabilidade de Auditoria – NBC TA e NBC PA","Amostragem em Auditoria – NBC TA 530","Testes de observância e testes substantivos","Testes para subavaliação e para superavaliação","Evidências e procedimentos de auditoria","Identificação de fraudes na escrita contábil","Demonstrações contábeis sujeitas a auditoria","Auditoria no ativo circulante: recomposição do fluxo de caixa","Identificação de saldo credor na conta caixa por falta de emissão de documentos fiscais","Suprimento das disponibilidades sem comprovação de origem dos recursos","Aquisições não contabilizadas e sem comprovação da origem do numerário","Baixa fictícia de títulos não recebidos e cotejamento de recebíveis","Auditoria no ativo não circulante e realizável a longo prazo","Auditoria em investimentos e no ativo imobilizado: ativos ocultos","Auditoria no ativo intangível","Auditoria no passivo circulante e não circulante","Passivos fictícios, identificação de passivos já pagos e não baixados","Auditoria no patrimônio líquido: capital social, reservas, subvenções","Auditoria em contas de resultado: receitas e despesas","Ocultação de receitas e superavaliação de custos e despesas","Identificação de fraudes na escrita fiscal","Auditoria na EFD e na Nota Fiscal Eletrônica (NFe)","Identificação de divergências fiscais em ICMS","Auditoria em operações de importação","Lei Complementar nº 105/2001 (sigilo das operações financeiras)"] },
      { nome: "Contabilidade Geral e Pública", topicos: ["Contabilidade: conceito, objeto, objetivos, campo de atuação e usuários","Princípios e Normas Brasileiras de Contabilidade (CFC)","Atos e fatos administrativos","Livros contábeis obrigatórios e documentação contábil","Variação do patrimônio líquido: receita, despesa, ganhos e perdas","Apuração dos resultados e regimes de apuração (caixa e competência)","Escrituração contábil: lançamentos, contas patrimoniais e de resultado","Fatos contábeis: permutativos, modificativos e mistos","Itens patrimoniais: conteúdo, estrutura, avaliação e classificação (ativo, passivo, PL)","Demonstrações contábeis: BP, DRE, DLPA, DMPL, DFC, DVA","Notas explicativas: conteúdo, forma e exigências legais","Ajustes pelas Leis nº 11.638/07 e 11.941/09","Estoques: tipos de inventários, critérios e métodos de avaliação","Apuração do CMV e tratamento contábil dos tributos nas compras e vendas","NBC TSP Estrutura Conceitual para o Setor Público","Relatório Contábil de Propósito Geral (RCPG): objetivos, usuários, accountability","Características qualitativas da informação contábil","Elementos das Demonstrações Contábeis do Setor Público","Reconhecimento e mensuração nas demonstrações do setor público","Estrutura e apresentação das Demonstrações Contábeis do Setor Público","Plano de Contas aplicado ao Setor Público (PCASP)","Lei Complementar nº 101/2000: dívida pública, RREO, RGF","Procedimentos Contábeis Orçamentários (MCASP)","Procedimentos Contábeis Patrimoniais (MCASP, 9ª edição)","Restos a pagar, empenho, liquidação e pagamento (Lei nº 4.320/1964)","NBC TSP 13: informação orçamentária nas demonstrações contábeis","Normas Internacionais de Contabilidade para o Setor Público (IPSAS)","Sistema de Informação de Custos do Setor Público (NBC T 16.11)"] },
      { nome: "Fluência em Dados", topicos: ["Conceitos, atributos, métricas e transformação de dados","Análise de dados: agrupamentos, tendências, projeções","Conceitos de Analytics, Aprendizado de Máquina e Inteligência Artificial","Processamento de Linguagem Natural","Governança de Dados: conceito e tipos (centralizada, compartilhada, colegiada)","Big Data: importância, arquitetura, modelos de entrega e distribuição de serviços","Ciência de Dados: ciclo de vida, papéis dos envolvidos em projetos","Computação em nuvem: plataformas para Big Data","Linguagens de programação para ciência de dados: Python e R","Bancos de dados NoSQL: modelos e principais SGBDs","Estatística descritiva aplicada a dados","Probabilidade e distribuições de probabilidade","Regressão linear simples e múltipla, regressão logística"] }
    ]
  },
  {
    modulo: "Módulo II – Conhecimentos Específicos",
    disciplinas: [
      { nome: "Direito Administrativo", topicos: ["Administração pública: princípios básicos","Poderes administrativos: hierárquico, disciplinar, regulamentar, de polícia","Uso e abuso do poder","Ato administrativo: conceito, requisitos e atributos","Anulação, revogação e convalidação do ato administrativo","Discricionariedade e vinculação","Organização administrativa: administração direta e indireta","Autarquias, fundações, empresas públicas, sociedades de economia mista","Consórcios públicos (Lei nº 11.107/2005)","Órgãos públicos: conceito, natureza e classificação","Servidores públicos: cargo, emprego e função públicos","Lei nº 8.112/1990: provimento, vacância, remoção, redistribuição e substituição","Lei nº 8.112/1990: direitos e vantagens, vencimento e remuneração, férias, licenças","Lei nº 8.112/1990: regime disciplinar, deveres, proibições, acumulação, penalidades","Processo administrativo disciplinar","Processo administrativo (Lei nº 9.784/1999)","Controle administrativo, judicial e legislativo da administração","Responsabilidade extracontratual do Estado","Improbidade Administrativa (Lei nº 8.429/1992)","Lei nº 11.416/2006","Nova Lei de Licitações e Contratos (Lei nº 14.133/2021)","Serviços públicos: conceito, regime jurídico, princípios, delegação (autorização, permissão, concessão)","Bens públicos: regime jurídico, classificação, utilização por terceiros","Intervenção do Estado na propriedade: desapropriação, servidão, tombamento, requisição","Terceiro Setor: Entes paraestatais"] },
      { nome: "Direito Constitucional", topicos: ["Teoria Geral do Estado e poderes do Estado","Teoria geral da Constituição: conceito, origens, conteúdo, estrutura, classificação","Supremacia da Constituição e tipos de Constituição","Poder constituinte","Os princípios constitucionais","Interpretação e controle de constitucionalidade","Normas constitucionais e inconstitucionais; competência dos tribunais","Efeitos da decisão no controle de constitucionalidade","Emenda, reforma e revisão constitucional","Hierarquia das normas jurídicas","Princípios fundamentais da Constituição da República Federativa do Brasil","Direitos e garantias fundamentais","Organização do Estado político-administrativo","Da Administração Pública e dos servidores públicos civis","Poder Legislativo: fiscalização contábil, financeira e orçamentária","Controle Externo, Sistemas de Controle Interno e TCU","Poder Executivo: Presidente, Vice-Presidente, atribuições, responsabilidade, Ministros","Poder Judiciário: disposições gerais, STF, STJ","O Ministério Público","Defesa do Estado e das instituições democráticas","Sistema Tributário Nacional e finanças públicas","Ordem econômica e financeira","Ordem social","Disposições gerais e disposições constitucionais transitórias"] },
      { nome: "Direito Previdenciário", topicos: ["Aspectos teóricos e conceituais da Seguridade Social e Previdência Social","Seguridade Social: origem, evolução legislativa, conceituação, organização e princípios","Legislação previdenciária: conteúdo, fontes, autonomia, vigência, hierarquia, interpretação","CNPS – Conselho Nacional de Previdência Social","Lei nº 8.213/1991 – Plano de Benefícios da Previdência Social","Lei nº 8.212/1991 – Custeio da Previdência Social","Plano de Benefícios: beneficiários, espécies, carência, salário de benefício, renda mensal","Manutenção, perda e restabelecimento da qualidade de segurado","Segurados obrigatórios: empregado, doméstico, contribuinte individual, trabalhador avulso","Segurado especial, MEI e segurado facultativo","Dependentes do RGPS: conceito, características, filiação e inscrição","Trabalhadores excluídos do Regime Geral","Financiamento da seguridade social: receitas da União e contribuições sociais","Salário de contribuição: conceito, parcelas integrantes e não integrantes, limites","Arrecadação e recolhimento das contribuições: obrigações da empresa e prazos","Responsabilidade solidária: construção civil, cessão de mão de obra, grupo econômico","Isenções e parcelamentos de contribuições: requisitos, manutenção e perda","Crimes contra a seguridade social e infrações previdenciárias","Equilíbrio financeiro e problemas estruturais da Previdência Social"] },
      { nome: "Direito Tributário", topicos: ["Competência Tributária","Limitações Constitucionais do Poder de Tributar: imunidades","Princípios Constitucionais Tributários","Conceito e Classificação dos Tributos","Tributos de Competência da União, dos Estados e dos Municípios","Simples Nacional","Legislação Tributária: fontes, vigência, aplicação","Interpretação e Integração da Legislação Tributária","Obrigação Tributária Principal e Acessória","Fato Gerador da Obrigação Tributária","Sujeição Ativa e Passiva, Solidariedade, Capacidade Tributária","Domicílio Tributário","Responsabilidade Tributária: dos sucessores, de terceiros e por infrações","Crédito Tributário: constituição e lançamento (modalidades)","Hipóteses de alteração do lançamento","Suspensão da Exigibilidade do Crédito Tributário: modalidades","Extinção do Crédito Tributário: modalidades","Pagamento Indevido","Exclusão do Crédito Tributário: modalidades","Garantias e Privilégios do Crédito Tributário","Administração Tributária: fiscalização, dívida ativa, certidões negativas","Sigilo Fiscal","Processo Administrativo Fiscal (Decreto nº 70.235/1972)","Crimes contra a ordem tributária (Lei nº 8.137/1990 e Lei nº 4.729/1965)","Ação cautelar fiscal","Lei de Liberdade Econômica e Direito Tributário (Lei nº 13.874/2019)","Tributação no regime falimentar","Planejamento Tributário: abuso de formas, interpretação econômica"] },
      { nome: "Legislação Tributária", topicos: ["Imposto sobre a Importação: fato gerador, contribuinte, base de cálculo, apuração","Imposto sobre a Exportação: fato gerador, contribuinte, base de cálculo, apuração","Imposto sobre a Propriedade Territorial Rural (ITR): competência, fato gerador, base de cálculo","Imposto de Renda – Pessoas Físicas: fato gerador, contribuintes, responsáveis, base de cálculo","IRPF: deduções, tributação exclusiva, carnê-leão, tributação definitiva, ajuste anual","Imposto de Renda – Pessoas Jurídicas: fato gerador, contribuintes, base de cálculo","IRPJ: despesas dedutíveis e indedutíveis, lucro real, presumido e arbitrado","IRPJ: lucros no exterior, preço de transferência, investimentos pelo método do PL","IRPJ: reorganizações societárias, tributação na fonte, regime de caixa e competência","Imposto sobre Produtos Industrializados (IPI): fato gerador, contribuinte, base de cálculo","IOF – Imposto sobre Operações de Crédito, Câmbio e Seguro","Contribuição para o PIS/Pasep e COFINS: regime de apuração cumulativa","Contribuição para o PIS/Pasep e COFINS: regime de apuração não cumulativa","Contribuição Social sobre o Lucro Líquido (CSLL)","CIDE-Combustíveis (Lei nº 10.336/2001)","CIDE-Tecnologia / Interação Universidade-Empresa (Lei nº 10.168/2000)"] },
      { nome: "Legislação Aduaneira", topicos: ["Jurisdição Aduaneira: território aduaneiro, portos, aeroportos, pontos de fronteira","Alfandegamento e Recintos Alfandegados","Administração Aduaneira","Controle Aduaneiro de Veículos","Imposto de Importação: incidência, fato gerador, base de cálculo, isenções e reduções","Imposto de Exportação: incidência, fato gerador, base de cálculo, incentivos fiscais","IPI vinculado à Importação","PIS/PASEP-Importação e COFINS-Importação","CIDE-Combustíveis na importação","Taxa de Utilização do Siscomex","Regime de Trânsito Aduaneiro","Admissão Temporária e Admissão Temporária para Aperfeiçoamento Ativo","Drawback","Entreposto Aduaneiro e RECOF","RECOM: importação de insumos para industrialização por encomenda","Exportação Temporária e Exportação Temporária para Aperfeiçoamento Passivo","REPETRO e REPEX","REPORTO – Regime Tributário para Incentivo à Modernização Portuária","Loja Franca, Depósito Especial, Depósito Afiançado e DAC","Zona Franca de Manaus, Áreas de Livre Comércio e ZPE","Despacho Aduaneiro de Importação: fases e procedimentos","Despacho Aduaneiro de Exportação e casos especiais","Revisão Aduaneira","Normas Especiais: naufrágio, abandono, avaria, extravio, tráfego postal e cabotagem","Infrações e Penalidades Aduaneiras: pena de perdimento, multas, sanções administrativas","Relevação de penalidades e representação fiscal para fins penais","Crédito Tributário Aduaneiro: lançamento de ofício, acréscimos, decadência, prescrição","Processos Fiscais: crédito tributário, perdimento, sanções, antidumping, consultas","Controle Administrativo Específico: destinação, processos e declarações","FUNDAF"] }
    ]
  }
];

// GET — retorna o edital com status do usuário
export async function GET() {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) return NextResponse.json([], { status: 401 });
  const uid = session.user.id as string;

  // Busca os dados salvos do usuário
  const saved = await prisma.editalTopico.findMany({ where: { userId: uid } });
  const savedMap = new Map(saved.map(s => [`${s.disciplina}|||${s.topico}`, s]));

  // Total de tópicos
  let totalTopicos = 0;
  let concluidos   = 0;

  const result = EDITAL_AFRFB.map(mod => ({
    modulo: mod.modulo,
    disciplinas: mod.disciplinas.map(disc => ({
      nome: disc.nome,
      topicos: disc.topicos.map((t, idx) => {
        totalTopicos++;
        const key  = `${disc.nome}|||${t}`;
        const dado = savedMap.get(key);
        if (dado?.concluido) concluidos++;
        return {
          nome:        t,
          ordem:       idx,
          concluido:   dado?.concluido   ?? false,
          questoes:    dado?.questoes    ?? 0,
          acertos:     dado?.acertos     ?? 0,
          erros:       dado?.erros       ?? 0,
          ultimoEstudo: dado?.ultimoEstudo ?? null,
        };
      }),
    })),
  }));

  return NextResponse.json({ totalTopicos, concluidos, modulos: result });
}

// PATCH — atualiza tópico (concluído, questões, acertos, erros)
export async function PATCH(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) return NextResponse.json({ message: "Não autorizado." }, { status: 401 });
  const uid = session.user.id as string;

  const { disciplina, topico, modulo, ordem, concluido, questoes, acertos, erros } = await req.json();
  if (!disciplina || !topico) return NextResponse.json({ message: "Dados inválidos." }, { status: 400 });

  await prisma.editalTopico.upsert({
    where:  { userId_disciplina_topico: { userId: uid, disciplina, topico } },
    create: { userId: uid, modulo, disciplina, topico, ordem: ordem ?? 0, concluido: concluido ?? false, questoes: questoes ?? 0, acertos: acertos ?? 0, erros: erros ?? 0, ultimoEstudo: concluido ? new Date() : null },
    update: { concluido: concluido ?? false, questoes: questoes ?? 0, acertos: acertos ?? 0, erros: erros ?? 0, updatedAt: new Date(), ...(concluido ? { ultimoEstudo: new Date() } : {}) },
  });

  return NextResponse.json({ ok: true });
}
